GENE_DB = {
    "BRCA1": {
        "disease": "Hereditary breast/ovarian cancer (risk)",
        "category": "Regulatory",
        "description": "Tumor suppressor involved in DNA double-strand break repair via homologous recombination and genome stability.",
        "protein_name": "Breast cancer type 1 susceptibility protein",
        "go_function": "DNA-binding transcription factor activity; damaged DNA binding; ubiquitin-protein transferase activity involved in DNA damage response.",
        "subcellular_location": "Nucleus (DNA repair foci), centrosome",
        "variants": [
            {"variant": "c.68_69delAG (p.Glu23Valfs*17)", "significance": "Pathogenic", "condition": "Hereditary breast and ovarian cancer", "note": "Founder frameshift variant (BRCA1 185delAG)."},
            {"variant": "c.5266dupC (p.Gln1756Profs*74)", "significance": "Pathogenic", "condition": "Hereditary breast and ovarian cancer", "note": "Frameshift variant (BRCA1 5382insC)."},
        ],
        "refseq_mrna": "NM_007294.4",
        "sequence": "ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTAGT",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
        "pdb_id": "1JNX",
    },
    "HTT": {
        "disease": "Huntington’s disease",
        "category": "Regulatory",
        "description": "Huntingtin is a large scaffolding protein implicated in neuronal function and intracellular transport; expanded CAG repeats cause neurodegeneration.",
        "protein_name": "Huntingtin",
        "go_function": "Scaffold protein involved in vesicle transport, synaptic transmission, and regulation of transcription.",
        "subcellular_location": "Cytoplasm, nucleus, neuronal processes",
        "variants": [
            {"variant": "CAG expansion (>36 repeats)", "significance": "Pathogenic", "condition": "Huntington's disease", "note": "Polyglutamine expansion in exon 1."},
        ],
        "refseq_mrna": "NM_002111.8",
        "sequence": "ATGGCGACCCTGGAAAAGCTGATGAAGGCCTTCGAGTCCCTCAAGTCCTTCCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAACAGCCGCCACCGCCGCCGCCGCCGCCGCCGCCTCCTCAGCTTCCTCAGCCGCCGCCGCAGGCACAGCCGCTGCTGCCTCAGCCGCAGCCGCCCCCGCCGCCGCCCCCGCCGCCACCCGGCCCG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
        "pdb_id": "6EZV",
    },
    "CFTR": {
        "disease": "Cystic fibrosis",
        "category": "Structural",
        "description": "ATP-gated chloride/bicarbonate channel in epithelial cells; regulates salt/water transport in airways, pancreas, and other tissues.",
        "protein_name": "Cystic fibrosis transmembrane conductance regulator",
        "go_function": "ATP-dependent chloride channel activity; bicarbonate transmembrane transporter activity; epithelial fluid secretion.",
        "subcellular_location": "Apical plasma membrane of epithelial cells",
        "variants": [
            {"variant": "p.Phe508del (F508del)", "significance": "Pathogenic", "condition": "Cystic fibrosis", "note": "Most common CF-causing variant; protein misfolding and ER retention."},
            {"variant": "p.Gly551Asp (G551D)", "significance": "Pathogenic", "condition": "Cystic fibrosis", "note": "Gating defect responsive to ivacaftor."},
        ],
        "refseq_mrna": "NM_000492.4",
        "sequence": "ATGCAGAGGTCGCCTCTGGAAAAGGCCAGCGTTGTCTCCAAACTTTTTTTCAGCTGGACCAGACCAATTTTGAGGAAAGGATACAGACAGCGCCTGGAATTGTCAGACATATACCAAATCCCTTCTGTTGATTCTGCTGACAATCTATCTGAAAAATTGGAAAGAGAATGGGATAGAGAGCTGGCTTCAAAGAAAAATCCTAAACTCATTAATGCCCTTCGGCGATGTTTTTTCTGGAGA",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
        "pdb_id": "5UAK",
    },
    "HBB": {
        "disease": "Sickle cell disease / beta-thalassemia",
        "category": "Structural",
        "description": "Beta subunit of hemoglobin; carries oxygen in red blood cells. Mutations can alter hemoglobin properties and RBC shape.",
        "protein_name": "Hemoglobin subunit beta",
        "go_function": "Oxygen transporter activity; hemoglobin complex binding; iron ion binding.",
        "subcellular_location": "Cytoplasm of erythrocytes",
        "variants": [
            {"variant": "p.Glu6Val (E6V)", "significance": "Pathogenic", "condition": "Sickle cell disease", "note": "Leads to hemoglobin S polymerization."},
            {"variant": "β0/β+ thalassemia mutations", "significance": "Pathogenic", "condition": "Beta-thalassemia", "note": "Reduced or absent beta-globin production."},
        ],
        "refseq_mrna": "NM_000518.5",
        "sequence": "ATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCTGGAC",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
        "pdb_id": "4HHB",
    },
    "DMD": {
        "disease": "Duchenne/Becker muscular dystrophy",
        "category": "Structural",
        "description": "Dystrophin links the cytoskeleton to the extracellular matrix in muscle, stabilizing the sarcolemma during contraction.",
        "protein_name": "Dystrophin",
        "go_function": "Actin binding; structural constituent of cytoskeleton; sarcolemma stabilization.",
        "subcellular_location": "Cytoplasmic side of sarcolemma in skeletal and cardiac muscle",
        "variants": [
            {"variant": "Exon deletions (e.g., exons 45–50)", "significance": "Pathogenic", "condition": "Duchenne/Becker muscular dystrophy", "note": "Out-of-frame vs in-frame deletions determine severity."},
        ],
        "refseq_mrna": "NM_004006.3",
        "sequence": "ATGCTTTGGTGGGAAGAAGTAGAGGACTGTTATGAAAGAGAAGATGTTCAAAAGAAAACATTCACAAAATGGGTAAATGCACAATTTTCTAAGTTTGGGAAGCAGCATATTGAGAACCTCTTCAGTGACCTACAGGATGGGAGGCGCCTCCTAGACCTCCTCGAAGGCCTGACAGGGCAAAAACTGCCAAAAGAAAAAGGATCCACAAGAGTTCATGCCCTGAACAATGTCAACAAGGCA",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "MYH7": {
        "disease": "Hypertrophic/dilated cardiomyopathy",
        "category": "Structural",
        "description": "Beta-myosin heavy chain is a major motor protein in cardiac muscle sarcomeres; variants affect contractility and heart function.",
        "protein_name": "Myosin-7 (beta-myosin heavy chain)",
        "go_function": "ATP-dependent motor activity; actin binding; force generation in cardiac muscle contraction.",
        "subcellular_location": "Sarcomere thick filament in cardiac and slow skeletal muscle",
        "variants": [
            {"variant": "p.Arg403Gln", "significance": "Pathogenic", "condition": "Hypertrophic cardiomyopathy", "note": "Classic MYH7 HCM missense variant."},
        ],
        "refseq_mrna": "NM_000257.4",
        "sequence": "ATGGGAGATTCGGAGATGGCAGTCTTTGGGGCTGCCGCCCCCTACCTGCGCAAGTCAGAGAAGGAGCGGCTAGAAGCGCAGACCAGGCCTTTTGACCTCAAGAAGGATGTCTTCGTGCCTGATGACAAACAGGAGTTTGTCAAGGCCAAGATCGTGTCTCGAGAGGGTGGCAAAGTCACTGCCGAGACCGAGTATGGCAAGACAGTGACCGTGAAGGAGGACCAGGTGATGCAGCAGAAC",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "APOE": {
        "disease": "Alzheimer’s disease (risk allele effects)",
        "category": "Metabolic",
        "description": "Apolipoprotein E transports cholesterol and lipids; influences neuronal repair and amyloid biology in the brain.",
        "protein_name": "Apolipoprotein E",
        "go_function": "Lipid transporter activity; cholesterol efflux mediator; receptor binding involved in lipoprotein metabolism.",
        "subcellular_location": "Secreted; plasma lipoprotein particles; brain extracellular space",
        "variants": [
            {"variant": "APOE*ε4 (p.Cys112Arg)", "significance": "Risk factor", "condition": "Late-onset Alzheimer’s disease", "note": "Increases Alzheimer’s risk."},
        ],
        "refseq_mrna": "NM_000041.4",
        "sequence": "ATGAAGGTTCTGTGGGCTGCGTTGCTGGTCACATTCCTGGCAGGATGCCAGGCCAAGGTGGAGCAAGCGGTGGAGACAGAGCCGGAGCCCGAGCTGCGCCAGCAGACCGAGTGGCAGAGCGGCCAGCGCTGGGAACTGGCACTGGGTCGCTTTTGGGATTACCTGCGCTGGGTGCAGACACTGTCTGAGCAGGTGCAGGAGGAGCTGCTCAGCTCCCAGGTCACCCAGGAACTGAGGGCG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "TP53": {
        "disease": "Cancer (tumor suppressor); Li-Fraumeni syndrome (risk)",
        "category": "Regulatory",
        "description": "p53 is a transcription factor that coordinates DNA damage responses, cell-cycle arrest, senescence, and apoptosis.",
        "protein_name": "Cellular tumor antigen p53",
        "go_function": "Sequence-specific DNA binding transcription factor activity; p53 binding; apoptotic signaling in response to DNA damage.",
        "subcellular_location": "Nucleus; cytoplasm; mitochondrion (stress-dependent)",
        "variants": [
            {"variant": "p.Arg175His", "significance": "Pathogenic", "condition": "Li-Fraumeni syndrome / various cancers", "note": "DNA-binding domain hotspot mutation."},
            {"variant": "p.Arg248Gln", "significance": "Pathogenic", "condition": "Multiple solid tumors", "note": "Contact hotspot mutant with dominant-negative effects."},
        ],
        "refseq_mrna": "NM_000546.6",
        "sequence": "ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCT",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
        "pdb_id": "1TUP",
    },
    "EGFR": {
        "disease": "Cancer (oncogenic signaling when mutated/amplified)",
        "category": "Regulatory",
        "description": "Epidermal growth factor receptor is a receptor tyrosine kinase that drives cell proliferation and survival signaling pathways.",
        "protein_name": "Epidermal growth factor receptor",
        "go_function": "Transmembrane receptor protein tyrosine kinase activity; EGF-activated signaling pathway; cell proliferation.",
        "subcellular_location": "Plasma membrane; endosomes",
        "variants": [
            {"variant": "Exon 19 deletion (e.g., E746_A750del)", "significance": "Pathogenic", "condition": "Non-small cell lung cancer", "note": "Sensitizing to EGFR TKIs."},
            {"variant": "p.Leu858Arg (L858R)", "significance": "Pathogenic", "condition": "Non-small cell lung cancer", "note": "Activating kinase-domain variant."},
        ],
        "refseq_mrna": "NM_005228.5",
        "sequence": "ATGCGACCCTCCGGGACGGCCGGGGCAGCGCTCCTGGCGCTGCTGGCTGCGCTCTGCCCGGCGAGTCGGGCTCTGGAGGAAAAGAAAGTTTGCCAAGGCACGAGTAACAAGCTCACGCAGTTGGGCACTTTTGAAGATCATTTTCTCAGCCTCCAGAGGATGTTCAATAACTGTGAGGTGGTCCTTGGGAATTTGGAAATTACCTATGTGCAGAGGAATTATGATCTTTCCTTCTTAAAG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "INS": {
        "disease": "Diabetes mellitus (monogenic forms; insulin production)",
        "category": "Metabolic",
        "description": "Insulin is a peptide hormone that regulates glucose uptake and metabolism, lowering blood glucose after meals.",
        "protein_name": "Insulin",
        "go_function": "Hormone activity; insulin receptor binding; regulation of glucose uptake and metabolism.",
        "subcellular_location": "Secreted; pancreatic beta-cell secretory granules",
        "variants": [
            {"variant": "p.Gly32Ser (MODY10)",
             "significance": "Pathogenic",
             "condition": "Maturity-onset diabetes of the young",
             "note": "Impairs insulin folding or secretion."},
        ],
        "refseq_mrna": "NM_000207.3",
        "sequence": "ATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "TNF": {
        "disease": "Inflammatory/autoimmune disease (cytokine pathway)",
        "category": "Regulatory",
        "description": "Tumor necrosis factor is a pro-inflammatory cytokine that orchestrates immune signaling and can induce apoptosis in some contexts.",
        "protein_name": "Tumor necrosis factor",
        "go_function": "Cytokine activity; TNF receptor binding; activation of NF-κB and apoptotic pathways.",
        "subcellular_location": "Type II membrane protein; secreted form in extracellular space",
        "variants": [
            {"variant": "c.-308G>A (promoter)", "significance": "Risk modifier", "condition": "Autoimmune and inflammatory conditions", "note": "Alters TNF expression levels."},
        ],
        "refseq_mrna": "NM_000594.4",
        "sequence": "ATGAGCACTGAAAGCATGATCCGGGACGTGGAGCTGGCCGAGGAGGCGCTCCCCAAGAAGACAGGGGGGCCCCAGGGCTCCAGGCGGTGCTTGTTCCTCAGCCTCTTCTCCTTCCTGATCGTGGCAGGCGCCACCACGCTCTTCTGCCTGCTGCACTTTGGAGTGATCGGCCCCCAGAGGGAAGAGTTCCCCAGGGACCTCTCTCTAATCAGCCCTCTGGCCCAGGCAGTCAGATCATCT",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "ACE2": {
        "disease": "Cardiovascular/renal physiology; viral entry receptor",
        "category": "Metabolic",
        "description": "ACE2 is a carboxypeptidase in the renin–angiotensin system; it modulates angiotensin peptides and is a receptor for some coronaviruses.",
        "protein_name": "Angiotensin-converting enzyme 2",
        "go_function": "Peptidyl-dipeptidase activity; carboxypeptidase activity in the renin–angiotensin system; viral receptor activity.",
        "subcellular_location": "Plasma membrane; apical surface of epithelial cells",
        "variants": [
            {"variant": "Multiple missense variants", "significance": "Risk modifier", "condition": "Cardiometabolic traits / infection susceptibility", "note": "Reported in population sequencing studies."},
        ],
        "refseq_mrna": "NM_021804.3",
        "sequence": "ATGTCAAGCTCTTCCTGGCTCCTTCTCAGCCTTGTTGCTGTAACTGCTGCTCAGTCCACCATTGAGGAACAGGCCAAGACATTTTTGGACAAGTTTAACCACGAAGCCGAAGACCTGTTCTATCAAAGTTCACTTGCTTCTTGGAATTATAACACCAATATTACTGAAGAGAATGTCCAAAACATGAATAATGCTGGGGACAAATGGTCTGCCTTTTTAAAGGAACAGTCCACACTTGCC",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "FMR1": {
        "disease": "Fragile X syndrome (CGG expansion)",
        "category": "Regulatory",
        "description": "RNA-binding protein that regulates translation at synapses; loss leads to neurodevelopmental phenotypes.",
        "protein_name": "Fragile X mental retardation protein 1",
        "go_function": "mRNA binding; translational repression at synapses; regulation of dendritic spine morphology.",
        "subcellular_location": "Cytoplasm; neuronal dendrites and synapses; nucleus",
        "variants": [
            {"variant": "CGG repeat expansion (>200 repeats)", "significance": "Pathogenic", "condition": "Fragile X syndrome", "note": "Leads to promoter methylation and loss of expression."},
        ],
        "refseq_mrna": "NM_002024.6",
        "sequence": "ATGGAGGAGCTGGTGGTGGAAGTGCGGGGCTCCAATGGCGCTTTCTACAAGGCATTTGTAAAGGATGTTCATGAAGATTCAATAACAGTTGCATTTGAAAACAACTGGCAGCCTGATAGGCAGATTCCATTTCATGATGTCAGATTCCCACCTCCTGTAGGTTATAATAAAGATATAAATGAAAGTGATGAAGTTGAGGTGTATTCCAGAGCAAATGAAAAAGAGCCTTGCTGTTGGTGG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "SMN1": {
        "disease": "Spinal muscular atrophy (SMN deficiency pathway)",
        "category": "Regulatory",
        "description": "SMN is required for snRNP assembly and pre-mRNA splicing; reduced SMN causes motor neuron degeneration.",
        "protein_name": "Survival motor neuron protein 1",
        "go_function": "RNA binding; assembly of spliceosomal snRNP complexes; regulation of mRNA splicing.",
        "subcellular_location": "Nucleus (gems), cytoplasm",
        "variants": [
            {"variant": "Exon 7 deletion", "significance": "Pathogenic", "condition": "Spinal muscular atrophy", "note": "Loss-of-function due to reduced full-length SMN1."},
        ],
        "refseq_mrna": "NM_000344.4",
        "sequence": "ATGGCGATGAGCAGCGGCGGCAGTGGTGGCGGCGTCCCGGAGCAGGAGGATTCCGTGCTGTTCCGGCGCGGCACAGGCCAGAGCGATGATTCTGACATTTGGGATGATACAGCACTGATAAAAGCATATGATAAAGCTGTGGCTTCATTTAAGCATGCTCTAAAGAATGGTGACATTTGTGAAACTTCGGGTAAACCAAAAACCACACCTAAAAGAAAACCTGCTAAGAAGAATAAAAGC",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "PAH": {
        "disease": "Phenylketonuria (PKU)",
        "category": "Metabolic",
        "description": "Phenylalanine hydroxylase converts phenylalanine to tyrosine; deficiency leads to phenylalanine accumulation and neurotoxicity.",
        "protein_name": "Phenylalanine-4-hydroxylase",
        "go_function": "Phenylalanine 4-monooxygenase activity; tetrahydrobiopterin-dependent aromatic amino acid hydroxylation.",
        "subcellular_location": "Cytosol of hepatocytes",
        "variants": [
            {"variant": "p.Arg408Trp", "significance": "Pathogenic", "condition": "Phenylketonuria", "note": "Common PAH missense variant reducing enzyme activity."},
        ],
        "refseq_mrna": "NM_000277.3",
        "sequence": "ATGTCCACTGCGGTCCTGGAAAACCCAGGCTTGGGCAGGAAACTCTCTGACTTTGGACAGGAAACAAGCTATATTGAAGACAACTGCAATCAAAATGGTGCCATATCACTGATCTTCTCACTCAAAGAAGAAGTTGGTGCATTGGCCAAAGTATTGCGCTTATTTGAGGAGAATGATGTAAACCTGACCCACATTGAATCTAGACCTTCTCGTTTAAAGAAAGATGAGTATGAATTTTTC",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "MTHFR": {
        "disease": "Hyperhomocysteinemia (risk variants); folate metabolism",
        "category": "Metabolic",
        "description": "Key enzyme in folate cycle producing 5-methyltetrahydrofolate, supporting methylation reactions and homocysteine remethylation.",
        "protein_name": "Methylenetetrahydrofolate reductase",
        "go_function": "5,10-methylenetetrahydrofolate reductase (NAD(P)H) activity; one-carbon metabolic process.",
        "subcellular_location": "Cytosol",
        "variants": [
            {"variant": "p.Ala222Val (C677T)", "significance": "Risk modifier", "condition": "Hyperhomocysteinemia / thrombophilia risk", "note": "Thermolabile variant with reduced activity."},
        ],
        "refseq_mrna": "NM_005957.5",
        "sequence": "ATGGTGAACGAAGCCAGAGGAAACAGCAGCCTCAACCCCTGCTTGGAGGGCAGTGCCAGCAGTGGCAGTGAGAGCTCCAAAGATAGTTCGAGATGTTCCACCCCGGGCCTGGACCCCGAGCGGCATGAGAGACTCCGGGAGAAGATGAGGCGGCGATTGGAATCTGGTGACAAGTGGTTCTCCCTGGAATTCTTCCCTCCTCGAACTGCTGAGGGAGCTGTCAATCTCATCTCAAGGTTT",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "KRAS": {
        "disease": "Cancer (RAS pathway oncogene)",
        "category": "Regulatory",
        "description": "Small GTPase molecular switch controlling proliferative signaling; oncogenic mutations lock KRAS in an active state.",
        "protein_name": "GTPase KRas",
        "go_function": "GTP binding; GTPase activity; signal transduction in RAS/MAPK pathway.",
        "subcellular_location": "Inner plasma membrane; endomembranes",
        "variants": [
            {"variant": "p.Gly12Asp (G12D)", "significance": "Pathogenic", "condition": "Colorectal and pancreatic cancer", "note": "Constitutively active RAS signaling."},
            {"variant": "p.Gly12Cys (G12C)", "significance": "Pathogenic", "condition": "Non-small cell lung cancer", "note": "Targetable with covalent KRAS G12C inhibitors."},
        ],
        "refseq_mrna": "NM_033360.4",
        "sequence": "ATGACTGAATATAAACTTGTGGTAGTTGGAGCTGGTGGCGTAGGCAAGAGTGCCTTGACGATACAGCTAATTCAGAATCATTTTGTGGACGAATATGATCCAACAATAGAGGATTCCTACAGGAAGCAAGTAGTAATTGATGGAGAAACCTGTCTCTTGGATATTCTCGACACAGCAGGTCAAGAGGAGTACAGTGCAATGAGGGACCAGTACATGAGGACTGGGGAGGGCTTTCTTTGT",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "BRAF": {
        "disease": "Cancer (MAPK pathway oncogene)",
        "category": "Regulatory",
        "description": "Serine/threonine kinase in the MAPK pathway; activating variants increase downstream ERK signaling and proliferation.",
        "protein_name": "Serine/threonine-protein kinase B-raf",
        "go_function": "Protein serine/threonine kinase activity; MAPK cascade signaling.",
        "subcellular_location": "Cytoplasm; plasma membrane (signal-dependent)",
        "variants": [
            {"variant": "p.Val600Glu (V600E)", "significance": "Pathogenic", "condition": "Melanoma and other cancers", "note": "Constitutive activation of BRAF kinase activity."},
        ],
        "refseq_mrna": "NM_004333.6",
        "sequence": "ATGGCGGCGCTGAGCGGTGGCGGTGGTGGCGGCGCGGAGCCGGGCCAGGCTCTGTTCAACGGGGACATGGAGCCCGAGGCCGGCGCCGGCGCCGGCGCCGCGGCCTCTTCGGCTGCGGACCCTGCCATTCCGGAGGAGGTGTGGAATATCAAACAAATGATTAAGTTGACACAGGAACATATAGAGGCCCTATTGGACAAATTTGGTGGGGAGCATAATCCACCATCAATATATCTGGAG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "SOD1": {
        "disease": "Amyotrophic lateral sclerosis (familial forms)",
        "category": "Metabolic",
        "description": "Antioxidant enzyme that converts superoxide radicals into oxygen and hydrogen peroxide; mutations can cause toxic protein aggregation.",
        "protein_name": "Superoxide dismutase [Cu-Zn]",
        "go_function": "Superoxide dismutase activity; detoxification of superoxide radicals.",
        "subcellular_location": "Cytosol; mitochondrial intermembrane space",
        "variants": [
            {"variant": "p.Ala4Val (A4V)", "significance": "Pathogenic", "condition": "Familial ALS", "note": "Aggressive ALS-associated missense variant."},
        ],
        "refseq_mrna": "NM_000454.5",
        "sequence": "ATGGCGACGAAGGCCGTGTGCGTGCTGAAGGGCGACGGCCCAGTGCAGGGCATCATCAATTTCGAGCAGAAGGAAAGTAATGGACCAGTGAAGGTGTGGGGAAGCATTAAAGGACTGACTGAAGGCCTGCATGGATTCCATGTTCATGAGTTTGGAGATAATACAGCAGGCTGTACCAGTGCAGGTCCTCACTTTAATCCTCTATCCAGAAAACACGGTGGGCCAAAGGATGAAGAGAGG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
    "PCSK9": {
        "disease": "Familial hypercholesterolemia (gain-of-function); low LDL (loss-of-function)",
        "category": "Metabolic",
        "description": "Secreted protease that regulates LDL receptor turnover; higher activity reduces LDLR and raises LDL cholesterol.",
        "protein_name": "Proprotein convertase subtilisin/kexin type 9",
        "go_function": "Serine-type endopeptidase activity; regulation of low-density lipoprotein receptor catabolic process.",
        "subcellular_location": "Secreted; extracellular space; endosomes",
        "variants": [
            {"variant": "p.Asp374Tyr", "significance": "Pathogenic", "condition": "Familial hypercholesterolemia", "note": "Gain-of-function variant increasing LDLR degradation."},
            {"variant": "p.Tyr142X", "significance": "Loss-of-function", "condition": "Hypocholesterolemia", "note": "Truncating variant associated with low LDL cholesterol."},
        ],
        "refseq_mrna": "NM_174936.4",
        "sequence": "ATGGGCACCGTCAGCTCCAGGCGGTCCTGGTGGCCGCTGCCACTGCTGCTGCTGCTGCTGCTGCTCCTGGGTCCCGCGGGCGCCCGTGCGCAGGAGGACGAGGACGGCGACTACGAGGAGCTGGTGCTAGCCTTGCGTTCCGAGGAGGACGGCCTGGCCGAAGCACCCGAGCACGGAACCACAGCCACCTTCCACCGCTGCGCCAAGGATCCGTGGAGGTTGCCTGGCACCTACGTGGTG",
        "sequence_note": "RefSeq CDS fragment (first 240 nt).",
    },
}

